### ISSUE TITLE
netviel not working with flask version 2.1.0

### ISSUE THREAD

**Issue by steffenfritz** [DavidMStraub/netviel#16]
_Error:_

```
[username@server ~]$ python -m netviel
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/username/.local/lib/python3.9/site-packages/netviel/__main__.py", line 1, in <module>
    from .api import create_app
  File "/home/username/.local/lib/python3.9/site-packages/netviel/api.py", line 12, in <module>
    from flask import Flask, current_app, g, send_file, send_from_directory, safe_join
ImportError: cannot import name 'safe_join' from 'flask' (/home/username/.local/lib/python3.9/site-packages/flask/__init__.py)
```

_Info:_

1. https://flask.palletsprojects.com/en/2.1.x/changes/#version-2-1-0

_Solution:_

"use werkzeug.utils.safe_join instead."

**Comment by pr3d1** [comment]
I have this problem too. I would be grateful if you could fix it
